#!/bin/bash
#
# Entrypoint for the rootless piler image. Based on jsuto/piler's
# docker/start.sh (piler is developed at https://github.com/jsuto/piler).
#
set -o errexit
set -o pipefail
set -o nounset

# Secret material (piler.key, .my.cnf, config with the DB password) is written
# here; owner-only until the explicit chmod 600 in give_it_to_piler.
umask 077

# Overridable so tests/entrypoint-config-test.sh can run fix_configs offline.
CONFIG_DIR="${CONFIG_DIR:-/etc/piler}"
PILER_CONF="${CONFIG_DIR}/piler.conf"
PILER_KEY="${CONFIG_DIR}/piler.key"
PILER_PEM="${CONFIG_DIR}/piler.pem"
PILER_NGINX_CONF="${CONFIG_DIR}/piler-nginx.conf"
CONFIG_SITE_PHP="${CONFIG_DIR}/config-site.php"
PILER_MY_CNF="${CONFIG_DIR}/.my.cnf"
RT="${RT:-1}"
MEMCACHED_HOSTNAME="${MEMCACHED_HOSTNAME:-memcached}"
MANTICORE_HOSTNAME="${MANTICORE_HOSTNAME:-manticore}"
# Manticore's SQL port is its own default; the read-only one is piler's
# convention. Both consumers, the daemon and the UI, follow MANTICORE_PORT.
MANTICORE_PORT="${MANTICORE_PORT:-9306}"
MANTICORE_PORT_READONLY="${MANTICORE_PORT_READONLY:-9307}"
MEMCACHED_PORT="${MEMCACHED_PORT:-11211}"
TMP_CONF_DIR="${TMP_CONF_DIR:-/tmp/piler-conf}"
PILER_USER="${PILER_USER:-piler}"
PILER_JS="${PILER_JS:-/var/piler/www/assets/js/piler.js}"
# Everything below it in config-site.php is rewritten on every start. Slash-free
# so it needs no escaping as a sed address.
CONFIG_SITE_MARKER="# generated by entrypoint, do not edit below this line"
# Listed once so the rename check and the conf_set calls cannot drift apart.
PILER_CONF_KEYS=(mysqlhost mysqluser mysqldb mysqlpwd hostid tls_enable sphxhost
                 sphxport rtindex mysqlsocket pidfile)

error() {
   echo "ERROR:" "$*" 1>&2
   exit 1
}

log() {
   echo "DEBUG:" "$*"
}

# `sed -i` renames a temp file over the target, which fails with "Device or
# resource busy" on a bind mount. Write into the existing inode instead.
safe_sed() {
   local target="$1"
   shift

   local tmp
   tmp="$(mktemp)"
   sed "$@" "$target" > "$tmp"
   cat "$tmp" > "$target"
   rm -f "$tmp"
}

# Escape a value for use as sed replacement text: backslash, ampersand and the
# delimiter are special, so a password containing them would corrupt the edit.
sed_replacement() {
   local delim="$1" s="$2"
   s="${s//\\/\\\\}"
   s="${s//&/\\&}"
   s="${s//"${delim}"/\\${delim}}"
   printf '%s' "$s"
}

# Rewrites the line when present, appends it when not: sed cannot add a line,
# and a piler.conf from a volume or a downstream template can legitimately lack
# a key this image sets. One function, so the escaping cannot be forgotten.
conf_set() {
   local file="$1" key="$2" value="$3"

   if grep -q "^${key}=" "$file"; then
      safe_sed "$file" "s/${key}=.*/${key}=$(sed_replacement / "$value")/g"
      return
   fi

   # Without a trailing newline the appended key joins the last line.
   if [[ -s "$file" && -n "$(tail -c1 "$file")" ]]; then
      printf '\n' >> "$file"
   fi
   printf '%s=%s\n' "$key" "$value" >> "$file"
}

# For a single-quoted PHP literal, where only backslash and quote are special.
php_single_quoted() {
   local s="$1"
   s="${s//\\/\\\\}"
   s="${s//\'/\\\'}"
   printf '%s' "$s"
}

# For a MariaDB option file. Unquoted, '#' starts a comment and a trailing space
# is trimmed, either of which truncates the value and gets the client denied.
my_cnf_value() {
   local s="$1"
   s="${s//\\/\\\\}"
   s="${s//\"/\\\"}"
   printf '"%s"' "$s"
}

# For a single-quoted SQL literal. MariaDB interprets backslash inside literals,
# so doubling the quote alone stores a different value than asked for.
sql_literal() {
   local s="$1"
   s="${s//\\/\\\\}"
   s="${s//\'/\'\'}"
   printf '%s' "$s"
}

pre_flight_check() {
   [[ -v PILER_HOSTNAME ]] || error "Missing PILER_HOSTNAME env variable"
   [[ -v MYSQL_HOSTNAME ]] || error "Missing MYSQL_HOSTNAME env variable"
   [[ -v MYSQL_DATABASE ]] || error "Missing MYSQL_DATABASE env variable"
   [[ -v MYSQL_USER ]]     || error "Missing MYSQL_USER env variable"
   [[ -v MYSQL_PASSWORD ]] || error "Missing MYSQL_PASSWORD env variable"
   # Real-time indexing only: manticore runs in a separate container with no
   # local `indexer`, so batch mode (RT=0) can't build or rotate indexes here.
   local port
   for port in MANTICORE_PORT MANTICORE_PORT_READONLY MEMCACHED_PORT; do
      [[ "${!port}" =~ ^[1-9][0-9]{0,4}$ ]] \
         || error "${port} must be a port number, got '${!port}'"
   done
   [[ "$RT" == "1" ]] || error "RT must be 1 (real-time mode), got RT='${RT}'. This image runs piler against an external manticore container with no local indexer binary, so any value other than 1 (including batch mode RT=0) is unsupported."
}

give_it_to_piler() {
   local f="$1"

   [[ -f "$f" ]] || error "${f} does not exist, aborting"

   chown "${PILER_USER}:${PILER_USER}" "$f"
   chmod 600 "$f"
}

make_certificate() {
   local f="$1"
   local crt="/tmp/1.cert"
   local SSL_CERT_DATA="/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"

   log "Making an ssl certificate"

   openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj "$SSL_CERT_DATA" -keyout "$f" -out "$crt" -sha256 2>/dev/null
   cat "$crt" >> "$f"
   rm -f "$crt"

   give_it_to_piler "$f"
}

make_piler_key() {
   local f="$1"

   log "Generating piler.key"

   dd if=/dev/urandom bs=56 count=1 of="$f" 2>/dev/null
   [[ $(stat -c '%s' "$f") -eq 56 ]] || error "could not read 56 bytes from /dev/urandom to ${f}"

   give_it_to_piler "$f"
}

write_piler_nginx_conf() {
   log "Writing ${PILER_NGINX_CONF}"

   cp "${TMP_CONF_DIR}/piler-nginx.conf.dist" "$PILER_NGINX_CONF"
   safe_sed "$PILER_NGINX_CONF" "s%PILER_HOST%$(sed_replacement % "$PILER_HOSTNAME")%"
}

fix_configs() {
   [[ -f "$PILER_KEY" ]] || make_piler_key "$PILER_KEY"
   [[ -f "$PILER_PEM" ]] || make_certificate "$PILER_PEM"

   # Also regenerate if an older template left it without a listen directive.
   if [[ ! -f "$PILER_NGINX_CONF" ]] || ! grep -q '^\s*listen\s' "$PILER_NGINX_CONF"; then
      write_piler_nginx_conf
   fi

   if [[ ! -f "$PILER_CONF" ]]; then
      cp "${TMP_CONF_DIR}/piler.conf.dist" "$PILER_CONF"
   fi

   log "Updating ${PILER_CONF}"

   # Checked against the shipped template, not the live file: that one comes
   # from the same package as the binary, so a key missing there means upstream
   # renamed it and this image would set one piler ignores.
   local key
   for key in "${PILER_CONF_KEYS[@]}"; do
      grep -q "^${key}=" "${TMP_CONF_DIR}/piler.conf.dist" \
         || error "no ${key}= line in ${TMP_CONF_DIR}/piler.conf.dist; piler renamed that key upstream, so this image would set one it ignores"
   done

   conf_set "$PILER_CONF" mysqlhost "$MYSQL_HOSTNAME"
   conf_set "$PILER_CONF" mysqluser "$MYSQL_USER"
   conf_set "$PILER_CONF" mysqldb "$MYSQL_DATABASE"
   conf_set "$PILER_CONF" mysqlpwd "$MYSQL_PASSWORD"
   conf_set "$PILER_CONF" hostid "$PILER_HOSTNAME"
   conf_set "$PILER_CONF" tls_enable 1
   conf_set "$PILER_CONF" sphxhost "$MANTICORE_HOSTNAME"
   conf_set "$PILER_CONF" sphxport "$MANTICORE_PORT"
   conf_set "$PILER_CONF" rtindex "$RT"
   conf_set "$PILER_CONF" mysqlsocket ""
   conf_set "$PILER_CONF" pidfile /var/piler/run/piler.pid

   give_it_to_piler "$PILER_CONF"

   if [[ ! -f "$CONFIG_SITE_PHP" ]]; then
      log "Writing ${CONFIG_SITE_PHP}"

      cp "${TMP_CONF_DIR}/config-site.dist.php" "$CONFIG_SITE_PHP"

      safe_sed "$CONFIG_SITE_PHP" "s%HOSTNAME%$(sed_replacement % "$PILER_HOSTNAME")%"

      # A template without a trailing newline would swallow the marker line.
      if [[ -n "$(tail -c1 "$CONFIG_SITE_PHP")" ]]; then
         printf '\n' >> "$CONFIG_SITE_PHP"
      fi
   fi

   log "Updating ${CONFIG_SITE_PHP}"

   # Upstream concatenates it with relative paths and defaults to '/', so it
   # needs both slashes. The quotes in piler.js are JS syntax, not part of the
   # value - passing them in used to be required there and broke the PHP side.
   local path_prefix=""
   if [[ -v PATH_PREFIX ]]; then
      [[ "$PATH_PREFIX" != *\'* ]] \
         || error "PATH_PREFIX must not contain a quote, got '${PATH_PREFIX}'; pass a bare path such as /piler/"
      path_prefix="/${PATH_PREFIX#/}"
      path_prefix="${path_prefix%/}/"
   fi

   # Only what the environment decides goes in the block: dropped and rewritten
   # every start, so a rotated password or a renamed service is picked up. PHP
   # keeps the last assignment, so these win over the template above the marker.
   safe_sed "$CONFIG_SITE_PHP" "/^${CONFIG_SITE_MARKER}\$/,\$d"

   {
      echo "$CONFIG_SITE_MARKER"
      echo "\$config['DB_HOSTNAME'] = '$(php_single_quoted "$MYSQL_HOSTNAME")';"
      echo "\$config['DB_DATABASE'] = '$(php_single_quoted "$MYSQL_DATABASE")';"
      echo "\$config['DB_USERNAME'] = '$(php_single_quoted "$MYSQL_USER")';"
      echo "\$config['DB_PASSWORD'] = '$(php_single_quoted "$MYSQL_PASSWORD")';"
      echo "\$memcached_server = ['$(php_single_quoted "$MEMCACHED_HOSTNAME")', ${MEMCACHED_PORT}];"
      echo "\$config['SPHINX_HOSTNAME'] = '$(php_single_quoted "$MANTICORE_HOSTNAME"):${MANTICORE_PORT}';"
      echo "\$config['SPHINX_HOSTNAME_READONLY'] = '$(php_single_quoted "$MANTICORE_HOSTNAME"):${MANTICORE_PORT_READONLY}';"
      if [[ -n "$path_prefix" ]]; then
         echo "\$config['PATH_PREFIX'] = '$(php_single_quoted "$path_prefix")';"
      fi
   } >> "$CONFIG_SITE_PHP"

   # Constants, so written only when absent: an integrated deployment may
   # legitimately override them and a standalone one has nothing else to supply
   # them. RELOAD_COMMAND calls rc.piler directly because everything here runs
   # as the same unprivileged user - no sudo/systemctl, which also sidesteps the
   # broken systemctl-probe default (jsuto #479).
   local setting key
   for setting in \
      "RT|1" \
      "SPHINX_MAIN_INDEX|'piler1'" \
      "MEMCACHED_ENABLED|1" \
      "DECRYPT_BINARY|'/usr/bin/pilerget'" \
      "DECRYPT_ATTACHMENT_BINARY|'/usr/bin/pileraget'" \
      "PILER_BINARY|'/usr/sbin/piler'" \
      "RELOAD_COMMAND|'/etc/init.d/rc.piler reload'"; do
      key="${setting%%|*}"
      grep -q "config\['${key}'\]" "$CONFIG_SITE_PHP" \
         || echo "\$config['${key}'] = ${setting#*|};" >> "$CONFIG_SITE_PHP"
   done

   if [[ -n "$path_prefix" ]]; then
      log "PATH_PREFIX normalized to ${path_prefix}"
      grep -q 'location\.origin' "$PILER_JS" \
         || error "no location.origin line in ${PILER_JS}, cannot apply PATH_PREFIX"
      safe_sed "$PILER_JS" \
         -e "s#location.origin + .*#location.origin + '$(sed_replacement '#' "$path_prefix")',#"
   fi

   # It carries the DB password in plaintext; lock it to piler:piler 600 like
   # piler.conf and .my.cnf, instead of leaving the template's permissions.
   give_it_to_piler "$CONFIG_SITE_PHP"
}

wait_until_mysql_server_is_ready() {
   local attempts=0
   local max_attempts="${MYSQL_WAIT_MAX_ATTEMPTS:-60}"

   until mysql "--defaults-file=${PILER_MY_CNF}" <<< "show databases" >/dev/null 2>&1; do
      attempts=$((attempts + 1))
      if [[ "$attempts" -ge "$max_attempts" ]]; then
         error "${MYSQL_HOSTNAME} not ready after ${max_attempts} attempts, giving up"
      fi
      log "${MYSQL_HOSTNAME} is not ready (${attempts}/${max_attempts})"
      sleep 5
   done

   log "${MYSQL_HOSTNAME} is ready"
}

init_database() {
   local table
   local has_metadata_table=0

   wait_until_mysql_server_is_ready

   while read -r table; do
      if [[ "$table" == metadata ]]; then has_metadata_table=1; fi
   done < <(mysql "--defaults-file=${PILER_MY_CNF}" "$MYSQL_DATABASE" <<< 'show tables')

   if [[ $has_metadata_table -eq 0 ]]; then
      log "no metadata table, creating tables"

      mysql "--defaults-file=${PILER_MY_CNF}" "$MYSQL_DATABASE" < /usr/share/piler/db-mysql.sql
   else
      log "metadata table exists"
   fi

   if [[ -v ADMIN_USER_PASSWORD_HASH ]]; then
      local admin_hash
      admin_hash="$(sql_literal "$ADMIN_USER_PASSWORD_HASH")"
      mysql "--defaults-file=${PILER_MY_CNF}" "$MYSQL_DATABASE" <<< "update user set password='${admin_hash}' where uid=0"
   fi
}

create_my_cnf_files() {
   # Ubuntu 26.04's mariadb-client defaults to requiring TLS on TCP
   # connections; the mariadb server in the compose stack has no SSL
   # configured, so the connection is refused.
   local host user pass
   host="$(my_cnf_value "$MYSQL_HOSTNAME")"
   user="$(my_cnf_value "$MYSQL_USER")"
   pass="$(my_cnf_value "$MYSQL_PASSWORD")"

   printf "[client]\nhost = %s\nuser = %s\npassword = %s\nssl = false\n[mysqldump]\nhost = %s\nuser = %s\npassword = %s\nssl = false\n" \
      "$host" "$user" "$pass" "$host" "$user" "$pass" \
      > "$PILER_MY_CNF"

   give_it_to_piler "$PILER_MY_CNF"
}

# Sourced by the tests to get the functions without starting anything.
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
   pre_flight_check
   fix_configs
   create_my_cnf_files
   init_database

   # piler and piler-smtp are supervisord programs; init_database() above
   # already waited for the database they need.
   exec "$@"
fi
