#!/bin/bash
#
# Offline tests for entrypoint.sh's config generation. No container, no
# database: fix_configs() is driven directly against a throwaway CONFIG_DIR,
# which is what makes the password-rotation and escaping cases cheap enough to
# run on every push.
#
set -o errexit
set -o pipefail
set -o nounset

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENTRYPOINT="${HERE}/../entrypoint.sh"

# Second entry point: one boot of fix_configs, in its own process, so each case
# gets the same fresh-environment semantics a real container start has.
if [[ "${1:-}" == "--boot" ]]; then
   # shellcheck source=../entrypoint.sh
   source "$ENTRYPOINT"

   # chown needs root and says nothing about the logic under test; keep the
   # chmod so the permission assertions below stay meaningful.
   give_it_to_piler() {
      [[ -f "$1" ]] || error "${1} does not exist, aborting"
      chmod 600 "$1"
   }
   # A 4096-bit key per boot would dominate the runtime.
   make_certificate() { : > "$1"; }

   fix_configs
   exit 0
fi

failures=0

ok() { printf 'ok   %s\n' "$1"; }
ko() { printf 'FAIL %s\n' "$1" >&2; failures=$((failures + 1)); }

check_eq() {
   local what="$1" want="$2" got="$3"
   if [[ "$want" == "$got" ]]; then ok "$what"; else
      ko "$what"
      printf '       want: %s\n       got : %s\n' "$want" "$got" >&2
   fi
}

check_file_has() {
   local what="$1" file="$2" pattern="$3"
   if grep -qF -- "$pattern" "$file"; then ok "$what"; else
      ko "$what"
      printf '       %s does not contain: %s\n' "$file" "$pattern" >&2
   fi
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

TMPL="${WORK}/templates"
mkdir -p "$TMPL"

# Stand-ins for the .dist files the image ships in /tmp/piler-conf. The key
# names here must match the shipped template exactly - that is the whole point
# of the last case below. Cross-check against the image with:
#   podman run --rm --entrypoint /bin/sh <image> \
#     -c 'grep -E "^(mysql|hostid|tls_enable|sphxhost|rtindex|pidfile)" \
#         /tmp/piler-conf/piler.conf.dist'
cat > "${TMPL}/piler.conf.dist" <<'EOF'
[piler]
mysql_connect_timeout=2
mysqlcharset=utf8mb4
mysqldb=piler
mysqlhost=
mysqlpwd=verystrongpassword
mysqlsocket=/var/run/mysqld/mysqld.sock
mysqluser=piler
hostid=localhost
tls_enable=0
sphxhost=127.0.0.1
rtindex=0
pidfile=/var/run/piler/piler.pid
EOF

# Deliberately without a trailing newline: the shipped template has none, and
# that is what would swallow the marker line.
printf '<?php\n$config = [];' > "${TMPL}/config-site.dist.php"

cat > "${TMPL}/manticore.conf" <<'EOF'
index piler1
{
    type = rt
    path = /var/lib/manticore/piler1
}
EOF

cat > "${TMPL}/piler-nginx.conf.dist" <<'EOF'
server {
    listen 80;
    server_name PILER_HOST;
}
EOF

# One boot in a fresh process. Extra "VAR=value" arguments are exported on top.
boot() {
   local config_dir="$1" password="$2"
   shift 2

   # Mirrors the shipped asset: "    base_url: location.origin + '/',".
   # KEEP_JS=1 leaves whatever the caller put there, to test a broken asset.
   local js="${config_dir}/piler.js"
   if [[ "${KEEP_JS:-0}" != 1 ]]; then
      printf "    base_url: location.origin + '/',\n" > "$js"
   fi

   (
      export CONFIG_DIR="$config_dir" TMP_CONF_DIR="$TMPL" PILER_JS="$js"
      export PILER_HOSTNAME="piler.example.com"
      export MYSQL_HOSTNAME="mysql" MYSQL_DATABASE="piler" MYSQL_USER="piler"
      export MYSQL_PASSWORD="$password"
      export MEMCACHED_HOSTNAME="memcached" MANTICORE_HOSTNAME="manticore"
      local kv
      for kv in "$@"; do export "${kv?}"; done
      bash "${BASH_SOURCE[0]}" --boot > /dev/null
   )
}

new_dir() {
   local d
   d="$(mktemp -d "${WORK}/case-XXXXXX")"
   printf '%s' "$d"
}

# Read one $config key back through PHP itself, which is the only thing that
# can tell us the escaping produced the intended value rather than a lookalike.
php_value() {
   php -r 'include $argv[1]; echo $config[$argv[2]];' "$1" "$2"
}

echo "# a first boot writes the generated config"

d="$(new_dir)"
boot "$d" 'piler123'
check_eq "piler.conf carries the password" \
   "mysqlpwd=piler123" "$(grep '^mysqlpwd=' "${d}/piler.conf")"
check_eq "piler.conf carries the host" \
   "mysqlhost=mysql" "$(grep '^mysqlhost=' "${d}/piler.conf")"
check_eq "rtindex is forced to 1" \
   "rtindex=1" "$(grep '^rtindex=' "${d}/piler.conf")"
check_file_has "config-site.php carries the password" \
   "${d}/config-site.php" "\$config['DB_PASSWORD'] = 'piler123';"
check_file_has "config-site.php points at manticore" \
   "${d}/config-site.php" "\$config['SPHINX_HOSTNAME'] = 'manticore:9306';"
check_file_has "config-site.php keeps RELOAD_COMMAND" \
   "${d}/config-site.php" "rc.piler reload"
check_eq "the marker survived a template with no trailing newline" \
   "1" "$(grep -cF 'generated by entrypoint' "${d}/config-site.php")"
check_eq "piler.conf is owner-only" "600" "$(stat -c '%a' "${d}/piler.conf")"
check_eq "config-site.php is owner-only" "600" "$(stat -c '%a' "${d}/config-site.php")"
check_eq "piler.key is 56 bytes" "56" "$(stat -c '%s' "${d}/piler.key")"

echo "# a rotated password reaches both files"

boot "$d" 'rotated-secret'
check_eq "piler.conf picked up the new password" \
   "mysqlpwd=rotated-secret" "$(grep '^mysqlpwd=' "${d}/piler.conf")"
check_file_has "config-site.php picked up the new password" \
   "${d}/config-site.php" "\$config['DB_PASSWORD'] = 'rotated-secret';"
check_eq "the old password is gone from config-site.php" \
   "0" "$(grep -cF 'piler123' "${d}/config-site.php")"

echo "# a renamed service reaches config-site.php"

boot "$d" 'rotated-secret' 'MANTICORE_HOSTNAME=search' 'MEMCACHED_HOSTNAME=cache'
check_file_has "SPHINX_HOSTNAME follows MANTICORE_HOSTNAME" \
   "${d}/config-site.php" "\$config['SPHINX_HOSTNAME'] = 'search:9306';"
check_file_has "the memcached server follows MEMCACHED_HOSTNAME" \
   "${d}/config-site.php" "\$memcached_server = ['cache', 11211];"

echo "# repeated boots neither grow the file nor lose hand edits"

d="$(new_dir)"
boot "$d" 'piler123'
# A hand edit above the marker must survive; one below it is by contract not
# preserved, which is what the marker text tells the reader.
sed -i "1a \$config['LANG'] = 'fr';" "${d}/config-site.php"
lines="$(wc -l < "${d}/config-site.php")"
for _ in 1 2 3; do boot "$d" 'piler123'; done
check_eq "the file did not grow over three more boots" \
   "$lines" "$(wc -l < "${d}/config-site.php")"
check_eq "exactly one marker" \
   "1" "$(grep -cF 'generated by entrypoint' "${d}/config-site.php")"
check_file_has "the hand edit above the marker survived" \
   "${d}/config-site.php" "\$config['LANG'] = 'fr';"

echo "# values that are special in PHP or sed are escaped, not injected"

# Backslash, single quote, ampersand, both sed delimiters used by the script,
# and a PHP snippet that would execute if the quoting broke.
tricky="a'b&c/d%e\\f\"g\$h"
d="$(new_dir)"
boot "$d" "$tricky"
check_eq "piler.conf holds the password verbatim" \
   "mysqlpwd=${tricky}" "$(grep '^mysqlpwd=' "${d}/piler.conf")"

if command -v php > /dev/null; then
   check_eq "config-site.php is valid PHP" \
      "No syntax errors detected in ${d}/config-site.php" \
      "$(php -l "${d}/config-site.php" 2>&1)"
   check_eq "PHP reads the password back byte for byte" \
      "$tricky" "$(php_value "${d}/config-site.php" DB_PASSWORD)"

   injection="x'; system('touch ${WORK}/pwned'); \$y = '"
   d="$(new_dir)"
   boot "$d" "$injection"
   check_eq "an injection attempt is valid PHP" \
      "No syntax errors detected in ${d}/config-site.php" \
      "$(php -l "${d}/config-site.php" 2>&1)"
   check_eq "the injection is read back as data" \
      "$injection" "$(php_value "${d}/config-site.php" DB_PASSWORD)"
   if [[ -e "${WORK}/pwned" ]]; then
      ko "including config-site.php executed the injected payload"
   else
      ok "including config-site.php executed nothing"
   fi
else
   echo "skip PHP assertions: no php binary"
fi

echo "# PATH_PREFIX reaches both the PHP config and the JS asset"

# Upstream concatenates it with relative paths and defaults to '/', so the value
# has to end up as /archive/ on both sides - quoted in the JS, bare in the PHP.
# Getting that split wrong is silent: the JS becomes a syntax error, or the PHP
# does, depending on which side the quotes were passed for.
for given in '/archive' 'archive/' '/archive/'; do
   d="$(new_dir)"
   boot "$d" 'piler123' "PATH_PREFIX=${given}"
   check_file_has "PATH_PREFIX=${given} normalizes in config-site.php" \
      "${d}/config-site.php" "\$config['PATH_PREFIX'] = '/archive/';"
   check_file_has "PATH_PREFIX=${given} normalizes in piler.js" \
      "${d}/piler.js" "location.origin + '/archive/',"
   check_file_has "PATH_PREFIX=${given} keeps the JS line prefix" \
      "${d}/piler.js" "base_url: location.origin"
done

d="$(new_dir)"
boot "$d" 'piler123' 'PATH_PREFIX=/'
check_file_has "PATH_PREFIX=/ stays /" \
   "${d}/config-site.php" "\$config['PATH_PREFIX'] = '/';"

d="$(new_dir)"
boot "$d" 'piler123'
check_eq "no PATH_PREFIX leaves the JS asset alone" \
   "    base_url: location.origin + '/'," "$(cat "${d}/piler.js")"
check_eq "no PATH_PREFIX writes no PHP key" \
   "0" "$(grep -cF "PATH_PREFIX" "${d}/config-site.php")"

# The old JS sed needed the quotes passed in, which broke the PHP side. Reject
# them with a message instead of writing one broken file or the other.
d="$(new_dir)"
if boot "$d" 'piler123' "PATH_PREFIX='/archive/'" 2> /dev/null; then
   ko "a quoted PATH_PREFIX was accepted"
else
   ok "a quoted PATH_PREFIX is rejected"
fi

d="$(new_dir)"
boot "$d" 'piler123'
: > "${d}/piler.js"
if KEEP_JS=1 boot "$d" 'piler123' 'PATH_PREFIX=/archive' 2> /dev/null; then
   ko "a piler.js without location.origin was accepted"
else
   ok "a piler.js without location.origin is rejected"
fi

echo "# a renamed key in the template fails loudly instead of silently"

# Every key the sed edits is checked, because a no-op sed leaves a stale
# password or hostname behind and says nothing. This is not hypothetical: the
# first version of this change edited `mysqlpassword=`, which does not exist -
# the key is `mysqlpwd=`.
for key in mysqlpwd mysqlhost hostid rtindex pidfile; do
   d="$(new_dir)"
   broken="${WORK}/broken-${key}"
   mkdir -p "$broken"
   cp "${TMPL}"/* "${broken}/"
   sed -i "/^${key}=/d" "${broken}/piler.conf.dist"
   if TMPL="$broken" boot "$d" 'piler123' 2> /dev/null; then
      ko "a piler.conf.dist without ${key}= was accepted"
   else
      ok "a piler.conf.dist without ${key}= is rejected"
   fi
done

echo
if [[ "$failures" -eq 0 ]]; then
   echo "all checks passed"
else
   echo "${failures} check(s) failed" >&2
   exit 1
fi
